#include "bolun/kernel.h"

int bolun_catalog_register_display_panel(void);
int bolun_catalog_register_framebuffer_console(void);
int bolun_catalog_register_lcd_backlight(void);
int bolun_catalog_register_mipi_dsi_host(void);
int bolun_catalog_register_touch_controller(void);
int bolun_catalog_register_gpu_command(void);
int bolun_catalog_register_opengles_loader(void);
int bolun_catalog_register_vulkan_loader(void);
int bolun_catalog_register_software_renderer(void);
int bolun_catalog_register_camera_sensor(void);
int bolun_catalog_register_camera_isp(void);
int bolun_catalog_register_audio_codec(void);
int bolun_catalog_register_audio_pcm_out(void);
int bolun_catalog_register_audio_pcm_in(void);
int bolun_catalog_register_speaker_amp(void);
int bolun_catalog_register_usb_host_core(void);
int bolun_catalog_register_usb_device_core(void);
int bolun_catalog_register_usb_otg(void);
int bolun_catalog_register_battery_gauge(void);
int bolun_catalog_register_charger_control(void);
int bolun_catalog_register_rtc_clock(void);
int bolun_catalog_register_gpio_controller(void);
int bolun_catalog_register_pwm_controller(void);
int bolun_catalog_register_i2c_controller(void);
int bolun_catalog_register_spi_controller(void);
int bolun_catalog_register_uart_controller(void);
int bolun_catalog_register_sdmmc_host(void);
int bolun_catalog_register_emmc_storage(void);
int bolun_catalog_register_nand_storage(void);
int bolun_catalog_register_wifi_radio(void);
int bolun_catalog_register_bluetooth_hci(void);
int bolun_catalog_register_nfc_nci(void);
int bolun_catalog_register_gps_gnss(void);
int bolun_catalog_register_vibrator_haptics(void);
int bolun_catalog_register_led_class(void);
int bolun_catalog_register_button_input(void);
int bolun_catalog_register_accelerometer_iio(void);
int bolun_catalog_register_gyroscope_iio(void);
int bolun_catalog_register_magnetometer_iio(void);
int bolun_catalog_register_ambient_light_iio(void);
int bolun_catalog_register_proximity_iio(void);
int bolun_catalog_register_thermal_zone(void);
int bolun_catalog_register_watchdog_timer(void);
int bolun_catalog_register_hardware_timer(void);
int bolun_catalog_register_dma_controller(void);
int bolun_catalog_register_power_controller(void);
int bolun_catalog_register_memory_controller(void);
int bolun_catalog_register_net_arp(void);
int bolun_catalog_register_net_icmpv4(void);
int bolun_catalog_register_net_icmpv6(void);
int bolun_catalog_register_net_ipv4(void);
int bolun_catalog_register_net_ipv6(void);
int bolun_catalog_register_net_tcp(void);
int bolun_catalog_register_net_udp(void);
int bolun_catalog_register_net_dhcp(void);
int bolun_catalog_register_net_dns(void);
int bolun_catalog_register_net_socket(void);
int bolun_catalog_register_net_route(void);
int bolun_catalog_register_net_netif(void);
int bolun_catalog_register_fs_fat32_mount(void);
int bolun_catalog_register_fs_fat32_format(void);
int bolun_catalog_register_fs_fat32_check(void);
int bolun_catalog_register_fs_ext4_mount(void);
int bolun_catalog_register_fs_ext4_format(void);
int bolun_catalog_register_fs_ext4_check(void);
int bolun_catalog_register_fs_journal(void);
int bolun_catalog_register_fs_autodetect(void);
int bolun_catalog_register_fs_block_cache(void);
int bolun_catalog_register_fs_mount_table(void);
int bolun_catalog_register_gui_desktop(void);
int bolun_catalog_register_gui_app_menu(void);
int bolun_catalog_register_gui_taskbar(void);
int bolun_catalog_register_gui_notifications(void);
int bolun_catalog_register_gui_lockscreen(void);
int bolun_catalog_register_gui_bootscreen(void);
int bolun_catalog_register_gui_settings(void);
int bolun_catalog_register_gui_file_manager(void);
int bolun_catalog_register_gui_terminal(void);
int bolun_catalog_register_gui_task_manager(void);
int bolun_catalog_register_gui_themes(void);
int bolun_catalog_register_gui_i18n(void);
int bolun_catalog_register_gui_software_compositor(void);
int bolun_catalog_register_gui_window_manager(void);
int bolun_catalog_register_gui_image_viewer(void);
int bolun_catalog_register_gui_pdf_viewer(void);
int bolun_catalog_register_app_browser(void);
int bolun_catalog_register_app_calculator(void);
int bolun_catalog_register_app_clock(void);
int bolun_catalog_register_app_calendar(void);
int bolun_catalog_register_app_notes(void);
int bolun_catalog_register_app_gallery(void);
int bolun_catalog_register_app_music(void);
int bolun_catalog_register_app_video(void);
int bolun_catalog_register_app_camera_app(void);
int bolun_catalog_register_app_contacts(void);
int bolun_catalog_register_app_messages(void);
int bolun_catalog_register_app_phone(void);
int bolun_catalog_register_app_files(void);
int bolun_catalog_register_app_terminal_app(void);
int bolun_catalog_register_app_recorder(void);
int bolun_catalog_register_app_store(void);
int bolun_catalog_register_service_installer(void);
int bolun_catalog_register_service_store_search(void);
int bolun_catalog_register_service_store_update(void);
int bolun_catalog_register_service_store_remove(void);
int bolun_catalog_register_service_store_signature(void);
int bolun_catalog_register_service_local_repo(void);
int bolun_catalog_register_service_dependency_resolver(void);
int bolun_catalog_register_service_update_check(void);
int bolun_catalog_register_service_update_install(void);
int bolun_catalog_register_service_update_rollback(void);
int bolun_catalog_register_service_update_integrity(void);

size_t bolun_driver_catalog_count(void)
{
    return 112u;
}

int bolun_driver_catalog_register_all(void)
{
    int registered = 0;
    if (bolun_catalog_register_display_panel() == 0) registered++;
    if (bolun_catalog_register_framebuffer_console() == 0) registered++;
    if (bolun_catalog_register_lcd_backlight() == 0) registered++;
    if (bolun_catalog_register_mipi_dsi_host() == 0) registered++;
    if (bolun_catalog_register_touch_controller() == 0) registered++;
    if (bolun_catalog_register_gpu_command() == 0) registered++;
    if (bolun_catalog_register_opengles_loader() == 0) registered++;
    if (bolun_catalog_register_vulkan_loader() == 0) registered++;
    if (bolun_catalog_register_software_renderer() == 0) registered++;
    if (bolun_catalog_register_camera_sensor() == 0) registered++;
    if (bolun_catalog_register_camera_isp() == 0) registered++;
    if (bolun_catalog_register_audio_codec() == 0) registered++;
    if (bolun_catalog_register_audio_pcm_out() == 0) registered++;
    if (bolun_catalog_register_audio_pcm_in() == 0) registered++;
    if (bolun_catalog_register_speaker_amp() == 0) registered++;
    if (bolun_catalog_register_usb_host_core() == 0) registered++;
    if (bolun_catalog_register_usb_device_core() == 0) registered++;
    if (bolun_catalog_register_usb_otg() == 0) registered++;
    if (bolun_catalog_register_battery_gauge() == 0) registered++;
    if (bolun_catalog_register_charger_control() == 0) registered++;
    if (bolun_catalog_register_rtc_clock() == 0) registered++;
    if (bolun_catalog_register_gpio_controller() == 0) registered++;
    if (bolun_catalog_register_pwm_controller() == 0) registered++;
    if (bolun_catalog_register_i2c_controller() == 0) registered++;
    if (bolun_catalog_register_spi_controller() == 0) registered++;
    if (bolun_catalog_register_uart_controller() == 0) registered++;
    if (bolun_catalog_register_sdmmc_host() == 0) registered++;
    if (bolun_catalog_register_emmc_storage() == 0) registered++;
    if (bolun_catalog_register_nand_storage() == 0) registered++;
    if (bolun_catalog_register_wifi_radio() == 0) registered++;
    if (bolun_catalog_register_bluetooth_hci() == 0) registered++;
    if (bolun_catalog_register_nfc_nci() == 0) registered++;
    if (bolun_catalog_register_gps_gnss() == 0) registered++;
    if (bolun_catalog_register_vibrator_haptics() == 0) registered++;
    if (bolun_catalog_register_led_class() == 0) registered++;
    if (bolun_catalog_register_button_input() == 0) registered++;
    if (bolun_catalog_register_accelerometer_iio() == 0) registered++;
    if (bolun_catalog_register_gyroscope_iio() == 0) registered++;
    if (bolun_catalog_register_magnetometer_iio() == 0) registered++;
    if (bolun_catalog_register_ambient_light_iio() == 0) registered++;
    if (bolun_catalog_register_proximity_iio() == 0) registered++;
    if (bolun_catalog_register_thermal_zone() == 0) registered++;
    if (bolun_catalog_register_watchdog_timer() == 0) registered++;
    if (bolun_catalog_register_hardware_timer() == 0) registered++;
    if (bolun_catalog_register_dma_controller() == 0) registered++;
    if (bolun_catalog_register_power_controller() == 0) registered++;
    if (bolun_catalog_register_memory_controller() == 0) registered++;
    if (bolun_catalog_register_net_arp() == 0) registered++;
    if (bolun_catalog_register_net_icmpv4() == 0) registered++;
    if (bolun_catalog_register_net_icmpv6() == 0) registered++;
    if (bolun_catalog_register_net_ipv4() == 0) registered++;
    if (bolun_catalog_register_net_ipv6() == 0) registered++;
    if (bolun_catalog_register_net_tcp() == 0) registered++;
    if (bolun_catalog_register_net_udp() == 0) registered++;
    if (bolun_catalog_register_net_dhcp() == 0) registered++;
    if (bolun_catalog_register_net_dns() == 0) registered++;
    if (bolun_catalog_register_net_socket() == 0) registered++;
    if (bolun_catalog_register_net_route() == 0) registered++;
    if (bolun_catalog_register_net_netif() == 0) registered++;
    if (bolun_catalog_register_fs_fat32_mount() == 0) registered++;
    if (bolun_catalog_register_fs_fat32_format() == 0) registered++;
    if (bolun_catalog_register_fs_fat32_check() == 0) registered++;
    if (bolun_catalog_register_fs_ext4_mount() == 0) registered++;
    if (bolun_catalog_register_fs_ext4_format() == 0) registered++;
    if (bolun_catalog_register_fs_ext4_check() == 0) registered++;
    if (bolun_catalog_register_fs_journal() == 0) registered++;
    if (bolun_catalog_register_fs_autodetect() == 0) registered++;
    if (bolun_catalog_register_fs_block_cache() == 0) registered++;
    if (bolun_catalog_register_fs_mount_table() == 0) registered++;
    if (bolun_catalog_register_gui_desktop() == 0) registered++;
    if (bolun_catalog_register_gui_app_menu() == 0) registered++;
    if (bolun_catalog_register_gui_taskbar() == 0) registered++;
    if (bolun_catalog_register_gui_notifications() == 0) registered++;
    if (bolun_catalog_register_gui_lockscreen() == 0) registered++;
    if (bolun_catalog_register_gui_bootscreen() == 0) registered++;
    if (bolun_catalog_register_gui_settings() == 0) registered++;
    if (bolun_catalog_register_gui_file_manager() == 0) registered++;
    if (bolun_catalog_register_gui_terminal() == 0) registered++;
    if (bolun_catalog_register_gui_task_manager() == 0) registered++;
    if (bolun_catalog_register_gui_themes() == 0) registered++;
    if (bolun_catalog_register_gui_i18n() == 0) registered++;
    if (bolun_catalog_register_gui_software_compositor() == 0) registered++;
    if (bolun_catalog_register_gui_window_manager() == 0) registered++;
    if (bolun_catalog_register_gui_image_viewer() == 0) registered++;
    if (bolun_catalog_register_gui_pdf_viewer() == 0) registered++;
    if (bolun_catalog_register_app_browser() == 0) registered++;
    if (bolun_catalog_register_app_calculator() == 0) registered++;
    if (bolun_catalog_register_app_clock() == 0) registered++;
    if (bolun_catalog_register_app_calendar() == 0) registered++;
    if (bolun_catalog_register_app_notes() == 0) registered++;
    if (bolun_catalog_register_app_gallery() == 0) registered++;
    if (bolun_catalog_register_app_music() == 0) registered++;
    if (bolun_catalog_register_app_video() == 0) registered++;
    if (bolun_catalog_register_app_camera_app() == 0) registered++;
    if (bolun_catalog_register_app_contacts() == 0) registered++;
    if (bolun_catalog_register_app_messages() == 0) registered++;
    if (bolun_catalog_register_app_phone() == 0) registered++;
    if (bolun_catalog_register_app_files() == 0) registered++;
    if (bolun_catalog_register_app_terminal_app() == 0) registered++;
    if (bolun_catalog_register_app_recorder() == 0) registered++;
    if (bolun_catalog_register_app_store() == 0) registered++;
    if (bolun_catalog_register_service_installer() == 0) registered++;
    if (bolun_catalog_register_service_store_search() == 0) registered++;
    if (bolun_catalog_register_service_store_update() == 0) registered++;
    if (bolun_catalog_register_service_store_remove() == 0) registered++;
    if (bolun_catalog_register_service_store_signature() == 0) registered++;
    if (bolun_catalog_register_service_local_repo() == 0) registered++;
    if (bolun_catalog_register_service_dependency_resolver() == 0) registered++;
    if (bolun_catalog_register_service_update_check() == 0) registered++;
    if (bolun_catalog_register_service_update_install() == 0) registered++;
    if (bolun_catalog_register_service_update_rollback() == 0) registered++;
    if (bolun_catalog_register_service_update_integrity() == 0) registered++;
    bolun_device_bind_all();
    return registered;
}
